language: java
script:
- mkdir target
- mkdir target/products
- cd target/products
- git clone https://github.com/Jose-Badeau/boomslang-geb.git
- git clone https://github.com/Jose-Badeau/boomslang-core.git
- git clone https://github.com/Jose-Badeau/boomslang-wireframesketcher
- cd boomslang-wireframesketcher
- git checkout release/4.7.0
- mvn clean install
- cd com.wireframesketcher.model.repository.remote
- mvn clean install
- cd ../../boomslang-core
- git checkout release/1.0.0
- mvn clean install
- cd ../boomslang-geb
- git checkout release/1.0.0
- mvn clean install
- cd ../../..
- mvn package -Pproduct
after_success:
- java -jar DirectoryCleaner.jar $BT_USER $BT_APIKEY jose-badeau boomslang updates
- bash -e ./deleteExistingP2Content.sh
- bash -e ./upload.sh $BT_USER $BT_APIKEY jose-badeau boomslang updates 1.0.0 target/build/final
env:
  global:
  - secure: YXXoDrT6csA2XO6oK1RFPT4I4rHxV+JG2WTlLvPq81g6hVQHkzLX/46ttIdOVxv3NlUPMBxfING5AOrNL+rh91q40TnSqKSXlvZgLt/5q0b10HeLsV53tHsClTRkyg4ruZIlM0D8dPXJ7mM9x5jcSfmKZm7mu8GzT2hWyf++EaB/zTQ1E6whOPWDyH02NiOY8n+aoCS5sz12trTE3n8JUB4ewxoFJKCKncXL1fnj+xCA53wkYpe/9OPxb1yXnVszVzcj1x+IZYmuS/UNqmEHC1rAXI/hxyNT2f1zPC2fAFjJLxyRxnt4DpnpDLSaiN2USWuOYMSa7FS7YKcm4hKHHy1HKBmn0pVOECVJZ0iZ/lhwuD6KCxmFYBpVSfeN5AZNS1+2SyZIJSrGDyqqUcR07+qfkGPx9dSk299GQ0iOT8FnuWzdDU+BhUWr/WlJeq8phXZ/6JtgrX/OwckdknHcgT3s2ETmoTvddUEsvjyKcsmbuqscfi0LHiUBoanUk4dqTQAaOUdTrrazC/ehu6guKpb3zdsyujSnJn/w1lXBPJX5SvjXUtw1Wy6Jngyc9Zub0pAsSvSxwOO67XDLNShdGPshErU4PHS8kZEFpLO35jJ56AF0x4UUHBK7UPQ3+tO5LDY/gKZ+18V51eS87LTmN99MFihg31GYvSJDZFNumyE=
  - secure: GjZEDC45HQGNB2KzRoMK/PdTctJOxxDrpTf1yNDyO65N6pRa46hCqejWCw/ubesuw5yPbnO/el02cGCZwf41+4YK90Ec+sBYGspGBEZEK8Bg5CK5hO1zXqkixHQXNDdRmC+0D9F4+QvpZlw7rCZzSPsNSplE7Q2PJfXFeQkiq/3ittWfmhyRemmxuRgnEGNOJu66/y182JTOymBh4mVuxaS6+Kac394vMpUsdSakWiYnGNQHT5fMJL9W9sND4LaUYmYeP5A9PkW4a5nrOYgeYJ4C6fqjKskfvl+OdVtsVEIy/5b9nt5U+BW8yb3sYbwgcXEVg4itHyw2z+RUUy5Fqb4oupaZVFlFim3ZHvtR5+RPGbJjaFEaWPCQn2qLRa/U0yNd/aIdyLsrD47EKX2gy6A1sExc01cX2IECQEkZVWe4xzOa41D7iPZite9mJkIgSk1kLOfvnFRa6ycnyRYoJMS4B++ZbLqSjHEgQXNi5B4Tw/vHV8Weiej3EENPBAfY9UGLWWP7YuL5COxdckq4F7rggygvPj3DOD8PrcpgjdsdkR+WcfXB9oEnhdIrbFvddJtjEQ2EUkq4CzxLdRBBYTNUfIGADuZbFKWjSIMx/PEWhYKfxuZAnHOEnT8AZJJAd9UwqzWNTsRK9pEUkOFDgZwRpeq3aRX9ACaFTvY1kJk=
